[ClassVersion("0.1.0.0"), FriendlyName("AdcsTemplate")]
class DSC_AdcsTemplate : OMI_BaseResource
{
    [Key, Description("Specifies the name of the CA template")] String Name;
    [Write, Description("Specifies whether the CA Template should be added or removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description()] String DisplayName;
    [Required, Description()] Int DefaultKeySpec;
    [Write, Description()] Int[] Flags;
    [Write, Description()] Int MaxIssuingDepth;
    [Write, Description()] String[] CriticalExtensions;
    [Write, Description()] String[] ExtendedKeyUsage;
    [Write, Description(), ValueMap{'Microsoft RSA SChannel Cryptographic Provider', 'Microsoft DH SChannel Cryptographic Provider', 'Microsoft Enhanced Cryptographic Provider v1.0', 'Microsoft Enhanced DSS and Diffie-Hellman Cryptographic Provider', 'Microsoft Enhanced RSA and AES Cryptographic Provider', 'Microsoft Strong Cryptographic Provider'}, Values{'Microsoft RSA SChannel Cryptographic Provider', 'Microsoft DH SChannel Cryptographic Provider', 'Microsoft Enhanced Cryptographic Provider v1.0', 'Microsoft Enhanced DSS and Diffie-Hellman Cryptographic Provider', 'Microsoft Enhanced RSA and AES Cryptographic Provider', 'Microsoft Strong Cryptographic Provider'}] String[] DefaultCSPs;
    [Write, Description()] Int RASignature;
    [Write, Description()] Int[] EnrollmentFlag;
    [Write, Description()] Int[] PrivateKeyFlag;
    [Write, Description()] Int[] CertificateNameFlag;
    [Write, Description()] Int MinimalKeySize;
    [Write, Description(), ValueMap{1, 2, 3, 4}, Values {1, 2, 3, 4}] Int TemplateSchemaVersion;
    [Write, Description()] String CertTemplateOID;
    [Write, Description()] String[] CertificateApplicationPolicy;
    [Write, Description()] Int[] KeyUsage;
    [Write, Description()] TimeSpan ExpirationPeriod;
    [Write, Description()] TimeSpan OverlapPeriod;
};
