[ClassVersion("0.1.0.0"), FriendlyName("AdcsCertificateTemplate")]
class DSC_AdcsCertificateTemplate : OMI_BaseResource
{
    [Key, Description("Specifies the name of the Certificate Template")] String Name;
    [Write, Description("Specifies whether the Certificate Template should be added or removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write] String DisplayName;
    [Required] Sint32 DefaultKeySpec;
    [Write] Sint32 Flags[];
    [Write] Sint32 MaxIssuingDepth;
    [Write] String CriticalExtensions[];
    [Write] String ExtendedKeyUsage[];
    [Write, ValueMap{"Microsoft RSA SChannel Cryptographic Provider", "Microsoft DH SChannel Cryptographic Provider", "Microsoft Enhanced Cryptographic Provider v1.0", "Microsoft Enhanced DSS and Diffie-Hellman Cryptographic Provider", "Microsoft Enhanced RSA and AES Cryptographic Provider", "Microsoft Strong Cryptographic Provider"}, Values{"Microsoft RSA SChannel Cryptographic Provider", "Microsoft DH SChannel Cryptographic Provider", "Microsoft Enhanced Cryptographic Provider v1.0", "Microsoft Enhanced DSS and Diffie-Hellman Cryptographic Provider", "Microsoft Enhanced RSA and AES Cryptographic Provider", "Microsoft Strong Cryptographic Provider"}] String DefaultCSPs[];
    [Write] Sint32 RASignature;
    [Write] Sint32 EnrollmentFlag[];
    [Write] Sint32 PrivateKeyFlag[];
    [Write] Sint32 CertificateNameFlag[];
    [Write] Sint32 MinimalKeySize;
    [Write, ValueMap{"1", "2", "3", "4"}, Values {"1", "2", "3", "4"}] Sint32 TemplateSchemaVersion;
    [Write] String CertTemplateOID;
    [Write] String CertificateApplicationPolicy[];
    [Write] Sint32 KeyUsage[];
    [Write] DATETIME ExpirationPeriod;
    [Write] DATETIME OverlapPeriod;
};
